# SPDX-FileCopyrightText: 2024 Sebastian Stöcker <sebastian.stoecker@uni-marburg.de>
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "Machbarkeit"
SPDX-PackageSupplier = "Nattika Jugkaeo <nattika.jugkaeo@uni-marburg.de>"
SPDX-PackageDownloadLocation = "https://github.com/diz-unimr/machbarkeit"

[[annotations]]
path = ["**.json", "composer.lock", ".github/renovate.json", ".vscode/**.json", "**.csv", "**.png", "**.env"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nattika Jugkaeo <nattika.jugkaeo@uni-marburg.de>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["l10n/**.js", "l10n/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nextcloud translators <https://www.transifex.com/nextcloud/>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
