# SPDX-FileCopyrightText: 2024 Sebastian Stöcker <sebastian.stoecker@uni-marburg.de>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "nc-dev"

services:
  nextcloud:
    image: ghcr.io/juliusknorr/nextcloud-dev-php81:latest
    environment:
      SERVER_BRANCH: v30.0.6
      SQL: pgsql
      PHP_XDEBUG_MODE: debug #develop
      NEXTCLOUD_AUTOINSTALL: "YES"
    volumes:
      - ./data/shared:/shared
      - ./data/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./data/server:/var/www/html
      - ./bootstrap.sh:/usr/local/bin/bootstrap.sh
      - ../:/var/www/html/apps-extra/machbarkeit
    ports:
      - "8080:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - database-pgsql

  database-pgsql:
    image: postgres:latest
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    image: ghcr.io/diz-unimr/machbarkeit-backend:1.2.11
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - BASE_URL=http://localhost:3000
      - AUTH__OIDC__ISSUER_URL
      - AUTH__OIDC__CLIENT_ID
      - AUTH__OIDC__CLIENT_SECRET=${CLIENT_SECRET}
      - CORS__ALLOW_ORIGIN=http://localhost:8080
      - MDR__ENDPOINT=https://mdr.diz.uni-marburg.de/api
      - DATABASE__URL=sqlite://db.sqlite?mode=rwc
    ports:
      - "3000:3000"

  query:
    image: ghcr.io/diz-unimr/machbarkeit-query:1.1.3
    environment:
      APP__LOG_LEVEL: debug
      FEASIBILITY__BASE_URL: https://feasibility.diz.uni-marburg.de/query/execute
      BROKER__URL: ws://backend:3000/feasibility/ws
      BROKER__AUTH__CLIENT_CREDENTIALS__CLIENT_ID: machbarkeit
      BROKER__AUTH__CLIENT_CREDENTIALS__CLIENT_SECRET: ${CLIENT_SECRET}
      BROKER__AUTH__CLIENT_CREDENTIALS__TOKEN_URL: ${TOKEN_URL}
    depends_on:
      - backend
