# SPDX-FileCopyrightText: 2024 Sebastian Stöcker <sebastian.stoecker@uni-marburg.de>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "nc-dev"

services:
  nextcloud:
    image: ghcr.io/juliushaertl/nextcloud-dev-php80:latest
    environment:
      SERVER_BRANCH: v27.1.5
      SQL: pgsql
      VIRTUAL_HOST: nextcloud.local
      PHP_XDEBUG_MODE: debug #develop
    volumes:
      - ./data/shared:/shared
      - ./data/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../:/var/www/html/apps-extra/machbarkeit
    ports:
      - "8080:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - database-pgsql

  database-pgsql:
    image: postgres:latest
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
