# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Package build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up npm7
        run: npm i -g npm@7
      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.2
        with:
          php-version: '8.1'
          tools: composer
      - name: Build & Package
        run: |
          make build-prod
      - uses: actions/upload-artifact@v4
        with:
          name: machbarkeit app tarball
          path: build/artifacts/machbarkeit.tar.gz
